server:
  port: 8082

payment-service:
  kafka:
    bootstrap-servers: localhost:29092
    group-id: payment-service
    orders-topic: postgres.public.orders
    payment-topic: payments
    retries-count: 2
    delay-ms: 1000
    message-size: 20971520
    topic-short-retention: 3600000
    schema-registry-url: http://localhost:8081
    simulate-error: false
  postgres:
    host: localhost:5433
    database: payment-db
    username: postgres
    password: postgres

spring:
  datasource:
    url: jdbc:postgresql://${payment-service.postgres.host}/${payment-service.postgres.database}?ApplicationName=${spring.application.name}
    username: ${payment-service.postgres.username}
    password: ${payment-service.postgres.password}
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
